// Al-Mathurat Sughra (ringkas). The 30-section order and repeat counts follow
// the akuislam.com guide (al-mathurat-pagi-sughra-ringkas-rumi).
// Sources:
// - Quran passages: Uthmani Arabic and Malay meaning (Tafsir Pimpinan
//   ar-Rahman, Abdullah Basmeih) from the Tanzil project via api.alquran.cloud.
// - Doa Arabic: traditional texts, checked against Hisnul Muslim where present.
// - Rumi and doa meanings: written for this app.
// Petang uses the same sections; a `petang` override swaps the pagi wording
// (asbahna -> amsaina, etc.).
// Generated by a one-off script; edit by hand, and have changes checked by
// an ustaz before publishing.

export const MATHURAT_SECTIONS = [
  {
    "id": 1,
    "kind": "quran",
    "title": "Al-Fatihah",
    "ref": "Surah al-Fatihah 1:1–7",
    "repeat": 1,
    "ayat": [
      {
        "n": 1,
        "ar": "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        "ms": "Dengan nama Allah, Yang Maha Pemurah, lagi Maha Mengasihani."
      },
      {
        "n": 2,
        "ar": "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ",
        "ms": "Segala puji tertentu bagi Allah, Tuhan yang memelihara dan mentadbirkan sekalian alam."
      },
      {
        "n": 3,
        "ar": "ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        "ms": "Yang Maha Pemurah, lagi Maha Mengasihani."
      },
      {
        "n": 4,
        "ar": "مَٰلِكِ يَوْمِ ٱلدِّينِ",
        "ms": "Yang Menguasai pemerintahan hari Pembalasan (hari Akhirat)."
      },
      {
        "n": 5,
        "ar": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
        "ms": "Engkaulah sahaja (Ya Allah) Yang Kami sembah, dan kepada Engkaulah sahaja kami memohon pertolongan."
      },
      {
        "n": 6,
        "ar": "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
        "ms": "Tunjukilah kami jalan yang lurus."
      },
      {
        "n": 7,
        "ar": "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
        "ms": "Iaitu jalan orang-orang yang Engkau telah kurniakan nikmat kepada mereka, bukan (jalan) orang-orang yang Engkau telah murkai, dan bukan pula (jalan) orang-orang yang sesat."
      }
    ],
    "rumi": "Bismillahir-rahmanir-rahim. Al-hamdu lillahi rabbil-'alamin. Ar-rahmanir-rahim. Maliki yaumid-din. Iyyaka na'budu wa iyyaka nasta'in. Ihdinas-siratal-mustaqim. Siratal-lazina an'amta 'alaihim, ghairil-maghdubi 'alaihim wa lad-dallin."
  },
  {
    "id": 2,
    "kind": "quran",
    "title": "Awal surah al-Baqarah",
    "ref": "Surah al-Baqarah 2:1–5",
    "repeat": 1,
    "ayat": [
      {
        "n": 1,
        "ar": "الٓمٓ",
        "ms": "Alif, Laam, Miim."
      },
      {
        "n": 2,
        "ar": "ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ",
        "ms": "Kitab Al-Quran ini, tidak ada sebarang syak padanya (tentang datangnya dari Allah dan tentang sempurnanya); ia pula menjadi petunjuk bagi orang-orang yang (hendak) bertaqwa;"
      },
      {
        "n": 3,
        "ar": "ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ",
        "ms": "Iaitu orang-orang yang beriman kepada perkara-perkara yang ghaib, dan mendirikan (mengerjakan) sembahyang serta membelanjakan (mendermakan) sebahagian dari rezeki yang Kami berikan kepada mereka."
      },
      {
        "n": 4,
        "ar": "وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْءَاخِرَةِ هُمْ يُوقِنُونَ",
        "ms": "Dan juga orang-orang yang beriman kepada Kitab \"Al-Quran\" yang diturunkan kepadamu (Wahai Muhammad), dan Kitab-kitab yang diturunkan dahulu daripadamu, serta mereka yakin akan (adanya) hari akhirat (dengan sepenuhnya)."
      },
      {
        "n": 5,
        "ar": "أُو۟لَٰٓئِكَ عَلَىٰ هُدًۭى مِّن رَّبِّهِمْ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ",
        "ms": "Mereka itulah yang tetap mendapat petunjuk dari Tuhan mereka, dan merekalah orang-orang yang berjaya."
      }
    ],
    "rumi": "Alif Lam Mim. Zalikal-kitabu la raiba fih, hudal lil-muttaqin. Allazina yu'minuna bil-ghaibi wa yuqimunas-solata wa mimma razaqnahum yunfiqun. Wallazina yu'minuna bima unzila ilaika wa ma unzila min qablik, wa bil-akhirati hum yuqinun. Ula'ika 'ala hudam mir-rabbihim, wa ula'ika humul-muflihun."
  },
  {
    "id": 3,
    "kind": "quran",
    "title": "Ayatul Kursi",
    "ref": "Surah al-Baqarah 2:255",
    "repeat": 1,
    "ayat": [
      {
        "n": 255,
        "ar": "ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌۭ وَلَا نَوْمٌۭ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ مَن ذَا ٱلَّذِى يَشْفَعُ عِندَهُۥٓ إِلَّا بِإِذْنِهِۦ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَىْءٍۢ مِّنْ عِلْمِهِۦٓ إِلَّا بِمَا شَآءَ ۚ وَسِعَ كُرْسِيُّهُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ ۖ وَلَا يَـُٔودُهُۥ حِفْظُهُمَا ۚ وَهُوَ ٱلْعَلِىُّ ٱلْعَظِيمُ",
        "ms": "Allah, tiada Tuhan (yang berhak disembah) melainkan Dia, Yang Tetap hidup, Yang Kekal selama-lamanya mentadbirkan (sekalian makhlukNya). Yang tidak mengantuk usahkan tidur. Yang memiliki segala yang ada di langit dan yang ada di bumi. Tiada sesiapa yang dapat memberi syafaat (pertolongan) di sisiNya melainkan dengan izinNya. yang mengetahui apa yang ada di hadapan mereka dan apa yang ada di belakang mereka, sedang mereka tidak mengetahui sesuatu pun dari (kandungan) ilmu Allah melainkan apa yang Allah kehendaki (memberitahu kepadanya). Luasnya Kursi Allah (ilmuNya dan kekuasaanNya) meliputi langit dan bumi; dan tiadalah menjadi keberatan kepada Allah menjaga serta memelihara keduanya. Dan Dia lah Yang Maha Tinggi (darjat kemuliaanNya), lagi Maha Besar (kekuasaanNya)"
      }
    ],
    "rumi": "Allahu la ilaha illa huw, al-hayyul-qayyum. La ta'khuzuhu sinatuw wa la naum. Lahu ma fis-samawati wa ma fil-ard. Man zal-lazi yasyfa'u 'indahu illa bi-iznih. Ya'lamu ma baina aidihim wa ma khalfahum, wa la yuhituna bisyai'im min 'ilmihi illa bima sya'. Wasi'a kursiyyuhus-samawati wal-ard, wa la ya'uduhu hifzuhuma, wa huwal-'aliyyul-'azim."
  },
  {
    "id": 4,
    "kind": "quran",
    "title": "Al-Baqarah ayat 256",
    "ref": "Surah al-Baqarah 2:256",
    "repeat": 1,
    "ayat": [
      {
        "n": 256,
        "ar": "لَآ إِكْرَاهَ فِى ٱلدِّينِ ۖ قَد تَّبَيَّنَ ٱلرُّشْدُ مِنَ ٱلْغَىِّ ۚ فَمَن يَكْفُرْ بِٱلطَّٰغُوتِ وَيُؤْمِنۢ بِٱللَّهِ فَقَدِ ٱسْتَمْسَكَ بِٱلْعُرْوَةِ ٱلْوُثْقَىٰ لَا ٱنفِصَامَ لَهَا ۗ وَٱللَّهُ سَمِيعٌ عَلِيمٌ",
        "ms": "Tidak ada paksaan dalam ugama (Islam), kerana sesungguhnya telah nyata kebenaran (Islam) dari kesesatan (kufur). Oleh itu, sesiapa yang tidak percayakan Taghut, dan ia pula beriman kepada Allah, maka sesungguhnya ia telah berpegang kepada simpulan (tali ugama) yang teguh yang tidak akan putus. Dan (ingatlah), Allah Maha Mendengar, lagi Maha Mengetahui."
      }
    ],
    "rumi": "La ikraha fid-din, qat-tabayyanar-rusydu minal-ghayy. Famay yakfur bit-taghuti wa yu'mim billahi faqadistamsaka bil-'urwatil-wusqa lanfisama laha, wallahu sami'un 'alim."
  },
  {
    "id": 5,
    "kind": "quran",
    "title": "Al-Baqarah ayat 257",
    "ref": "Surah al-Baqarah 2:257",
    "repeat": 1,
    "ayat": [
      {
        "n": 257,
        "ar": "ٱللَّهُ وَلِىُّ ٱلَّذِينَ ءَامَنُوا۟ يُخْرِجُهُم مِّنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِ ۖ وَٱلَّذِينَ كَفَرُوٓا۟ أَوْلِيَآؤُهُمُ ٱلطَّٰغُوتُ يُخْرِجُونَهُم مِّنَ ٱلنُّورِ إِلَى ٱلظُّلُمَٰتِ ۗ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ",
        "ms": "Allah Pelindung (Yang mengawal dan menolong) orang-orang yang beriman. Ia mengeluarkan mereka dari kegelapan (kufur) kepada cahaya (iman). Dan orang-orang yang kafir, penolong-penolong mereka ialah Taghut yang mengeluarkan mereka dari cahaya (iman) kepada kegelapan (kufur). Mereka itulah ahli neraka, mereka kekal di dalamnya."
      }
    ],
    "rumi": "Allahu waliyyul-lazina amanu yukhrijuhum minaz-zulumati ilan-nur. Wallazina kafaru auliya'uhumut-taghutu yukhrijunahum minan-nuri ilaz-zulumat. Ula'ika ashabun-nar, hum fiha khalidun."
  },
  {
    "id": 6,
    "kind": "quran",
    "title": "Al-Baqarah ayat 284",
    "ref": "Surah al-Baqarah 2:284",
    "repeat": 1,
    "ayat": [
      {
        "n": 284,
        "ar": "لِّلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ وَإِن تُبْدُوا۟ مَا فِىٓ أَنفُسِكُمْ أَوْ تُخْفُوهُ يُحَاسِبْكُم بِهِ ٱللَّهُ ۖ فَيَغْفِرُ لِمَن يَشَآءُ وَيُعَذِّبُ مَن يَشَآءُ ۗ وَٱللَّهُ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌ",
        "ms": "Segala yang ada di langit dan yang ada di bumi adalah kepunyaan Allah. Dan jika kamu melahirkan apa yang ada di dalam hati kamu atau kamu memyembunyikannya, nescaya Allah akan menghitung dan menyatakannya kepada kamu. Kemudian Ia mengampunkan bagi sesiapa yang dikehendakiNya dan menyeksa sesiapa yang dikehendakiNya (menurut undang-undang peraturanNya) Dan (ingatlah), Allah Maha Kuasa atas tiap-tiap sesuatu."
      }
    ],
    "rumi": "Lillahi ma fis-samawati wa ma fil-ard. Wa in tubdu ma fi anfusikum au tukhfuhu yuhasibkum bihillah. Fayaghfiru limay yasya'u wa yu'azzibu may yasya'. Wallahu 'ala kulli syai'in qadir."
  },
  {
    "id": 7,
    "kind": "quran",
    "title": "Al-Baqarah ayat 285",
    "ref": "Surah al-Baqarah 2:285",
    "repeat": 1,
    "ayat": [
      {
        "n": 285,
        "ar": "ءَامَنَ ٱلرَّسُولُ بِمَآ أُنزِلَ إِلَيْهِ مِن رَّبِّهِۦ وَٱلْمُؤْمِنُونَ ۚ كُلٌّ ءَامَنَ بِٱللَّهِ وَمَلَٰٓئِكَتِهِۦ وَكُتُبِهِۦ وَرُسُلِهِۦ لَا نُفَرِّقُ بَيْنَ أَحَدٍۢ مِّن رُّسُلِهِۦ ۚ وَقَالُوا۟ سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ ٱلْمَصِيرُ",
        "ms": "Rasulullah telah beriman kepada apa yang diturunkan kepadanya dari Tuhannya, dan juga orang-orang yang beriman; semuanya beriman kepada Allah, dan Malaikat-malaikatNya, dan Kitab-kitabNya, dan Rasul-rasulNya. (Mereka berkata): \"Kami tidak membezakan antara seorang dengan yang lain Rasul-rasulnya\". Mereka berkata lagi: Kami dengar dan kami taat (kami pohonkan) keampunanMu wahai Tuhan kami, dan kepadaMu jualah tempat kembali\"."
      }
    ],
    "rumi": "Amanar-rasulu bima unzila ilaihi mir-rabbihi wal-mu'minun. Kullun amana billahi wa mala'ikatihi wa kutubihi wa rusulih. La nufarriqu baina ahadim mir-rusulih. Wa qalu sami'na wa ata'na, ghufranaka rabbana wa ilaikal-masir."
  },
  {
    "id": 8,
    "kind": "quran",
    "title": "Al-Baqarah ayat 286",
    "ref": "Surah al-Baqarah 2:286",
    "repeat": 1,
    "ayat": [
      {
        "n": 286,
        "ar": "لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا ٱكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَآ إِن نَّسِينَآ أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَآ إِصْرًۭا كَمَا حَمَلْتَهُۥ عَلَى ٱلَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِۦ ۖ وَٱعْفُ عَنَّا وَٱغْفِرْ لَنَا وَٱرْحَمْنَآ ۚ أَنتَ مَوْلَىٰنَا فَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَٰفِرِينَ",
        "ms": "Allah tidak memberati seseorang melainkan apa yang terdaya olehnya. Ia mendapat pahala kebaikan yang diusahakannya, dan ia juga menanggung dosa kejahatan yang diusahakannya. (Mereka berdoa dengan berkata): \"Wahai Tuhan kami! Janganlah Engkau mengirakan kami salah jika kami lupa atau kami tersalah. Wahai Tuhan kami ! Janganlah Engkau bebankan kepada kami bebanan yang berat sebagaimana yang telah Engkau bebankan kepada orang-orang yang terdahulu daripada kami. Wahai Tuhan kami! Janganlah Engkau pikulkan kepada kami apa yang kami tidak terdaya memikulnya. Dan maafkanlah kesalahan kami, serta ampunkanlah dosa kami, dan berilah rahmat kepada kami. Engkaulah Penolong kami; oleh itu, tolonglah kami untuk mencapai kemenangan terhadap kaum-kaum yang kafir\"."
      }
    ],
    "rumi": "La yukallifullahu nafsan illa wus'aha. Laha ma kasabat wa 'alaiha mak-tasabat. Rabbana la tu'akhizna in nasina au akhta'na. Rabbana wa la tahmil 'alaina isran kama hamaltahu 'alal-lazina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa'fu 'anna, waghfir lana, warhamna. Anta maulana fansurna 'alal-qaumil-kafirin."
  },
  {
    "id": 9,
    "kind": "quran",
    "title": "Al-Ikhlas",
    "ref": "Surah al-Ikhlas 112:1–4",
    "repeat": 3,
    "ayat": [
      {
        "n": 1,
        "ar": "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
        "ms": "Katakanlah (wahai Muhammad): \"(Tuhanku) ialah Allah Yang Maha Esa;"
      },
      {
        "n": 2,
        "ar": "ٱللَّهُ ٱلصَّمَدُ",
        "ms": "\"Allah Yang menjadi tumpuan sekalian makhluk untuk memohon sebarang hajat;"
      },
      {
        "n": 3,
        "ar": "لَمْ يَلِدْ وَلَمْ يُولَدْ",
        "ms": "\"Ia tiada beranak, dan Ia pula tidak diperanakkan;"
      },
      {
        "n": 4,
        "ar": "وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
        "ms": "\"Dan tidak ada sesiapapun yang serupa denganNya\"."
      }
    ],
    "rumi": "Qul huwallahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad."
  },
  {
    "id": 10,
    "kind": "quran",
    "title": "Al-Falaq",
    "ref": "Surah al-Falaq 113:1–5",
    "repeat": 3,
    "ayat": [
      {
        "n": 1,
        "ar": "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ",
        "ms": "Katakanlah (wahai Muhammad); \"Aku berlindung kepada (Allah) Tuhan yang menciptakan sekalian makhluk,"
      },
      {
        "n": 2,
        "ar": "مِن شَرِّ مَا خَلَقَ",
        "ms": "\"Dari bencana makhluk-makhluk yang Ia ciptakan;"
      },
      {
        "n": 3,
        "ar": "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
        "ms": "\"Dan dari bahaya gelap apabila ia masuk;"
      },
      {
        "n": 4,
        "ar": "وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ",
        "ms": "\"Dan dari kejahatan makhluk-makhluk yang menghembus-hembus pada simpulan-simpulan (dan ikatan-ikatan);"
      },
      {
        "n": 5,
        "ar": "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
        "ms": "\"Dan dari kejahatan orang yang dengki apabila ia melakukan dengkinya\"."
      }
    ],
    "rumi": "Qul a'uzu birabbil-falaq. Min syarri ma khalaq. Wa min syarri ghasiqin iza waqab. Wa min syarrin-naffasati fil-'uqad. Wa min syarri hasidin iza hasad."
  },
  {
    "id": 11,
    "kind": "quran",
    "title": "An-Nas",
    "ref": "Surah an-Nas 114:1–6",
    "repeat": 3,
    "ayat": [
      {
        "n": 1,
        "ar": "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
        "ms": "Katakanlah (wahai Muhammad): \"Aku berlindung kepada (Allah) Pemulihara sekalian manusia."
      },
      {
        "n": 2,
        "ar": "مَلِكِ ٱلنَّاسِ",
        "ms": "\"Yang Menguasai sekalian manusia,"
      },
      {
        "n": 3,
        "ar": "إِلَٰهِ ٱلنَّاسِ",
        "ms": "\"Tuhan yang berhak disembah oleh sekalian manusia,"
      },
      {
        "n": 4,
        "ar": "مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ",
        "ms": "\"Dari kejahatan pembisik penghasut yang timbul tenggelam, -"
      },
      {
        "n": 5,
        "ar": "ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ",
        "ms": "\"Yang melemparkan bisikan dan hasutannya ke dalam hati manusia, -"
      },
      {
        "n": 6,
        "ar": "مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
        "ms": "\"(Iaitu pembisik dan penghasut) dari kalangan jin dan manusia\"."
      }
    ],
    "rumi": "Qul a'uzu birabbin-nas. Malikin-nas. Ilahin-nas. Min syarril-waswasil-khannas. Allazi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas."
  },
  {
    "id": 12,
    "kind": "doa",
    "title": "Pujian kepada Allah",
    "repeat": 3,
    "ar": "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلّٰهِ، وَالْحَمْدُ لِلّٰهِ، لَا شَرِيكَ لَهُ، لَا إِلٰهَ إِلَّا هُوَ، وَإِلَيْهِ النُّشُورُ",
    "rumi": "Asbahna wa asbahal-mulku lillah, wal-hamdu lillah, la syarika lah, la ilaha illa huwa wa ilaihin-nusyur.",
    "ms": "Kami berpagi hari dan kerajaan (seluruh alam) berpagi hari milik Allah. Segala puji bagi Allah, tiada sekutu bagi-Nya, tiada tuhan melainkan Dia, dan kepada-Nya jua tempat kebangkitan.",
    "petang": {
      "ar": "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلّٰهِ، وَالْحَمْدُ لِلّٰهِ، لَا شَرِيكَ لَهُ، لَا إِلٰهَ إِلَّا هُوَ، وَإِلَيْهِ الْمَصِيرُ",
      "rumi": "Amsaina wa amsal-mulku lillah, wal-hamdu lillah, la syarika lah, la ilaha illa huwa wa ilaihil-masir.",
      "ms": "Kami berpetang hari dan kerajaan (seluruh alam) berpetang hari milik Allah. Segala puji bagi Allah, tiada sekutu bagi-Nya, tiada tuhan melainkan Dia, dan kepada-Nya jua tempat kembali."
    }
  },
  {
    "id": 13,
    "kind": "doa",
    "title": "Teguh di atas fitrah Islam",
    "repeat": 1,
    "ar": "أَصْبَحْنَا عَلَى فِطْرَةِ الْإِسْلَامِ، وَعَلَى كَلِمَةِ الْإِخْلَاصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ حَنِيفًا مُسْلِمًا، وَمَا كَانَ مِنَ الْمُشْرِكِينَ",
    "rumi": "Asbahna 'ala fitratil-islam, wa 'ala kalimatil-ikhlas, wa 'ala dini nabiyyina Muhammadin sallallahu 'alaihi wa sallam, wa 'ala millati abina Ibrahima hanifam muslima, wa ma kana minal-musyrikin.",
    "ms": "Kami berpagi hari di atas fitrah Islam, di atas kalimah ikhlas, di atas agama Nabi kami Muhammad ﷺ, dan di atas millah bapa kami Ibrahim yang lurus lagi berserah diri, dan dia bukanlah daripada golongan musyrikin.",
    "petang": {
      "ar": "أَمْسَيْنَا عَلَى فِطْرَةِ الْإِسْلَامِ، وَعَلَى كَلِمَةِ الْإِخْلَاصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ حَنِيفًا مُسْلِمًا، وَمَا كَانَ مِنَ الْمُشْرِكِينَ",
      "rumi": "Amsaina 'ala fitratil-islam, wa 'ala kalimatil-ikhlas, wa 'ala dini nabiyyina Muhammadin sallallahu 'alaihi wa sallam, wa 'ala millati abina Ibrahima hanifam muslima, wa ma kana minal-musyrikin.",
      "ms": "Kami berpetang hari di atas fitrah Islam, di atas kalimah ikhlas, di atas agama Nabi kami Muhammad ﷺ, dan di atas millah bapa kami Ibrahim yang lurus lagi berserah diri, dan dia bukanlah daripada golongan musyrikin."
    }
  },
  {
    "id": 14,
    "kind": "doa",
    "title": "Mensyukuri nikmat",
    "repeat": 3,
    "ar": "اللّٰهُمَّ إِنِّي أَصْبَحْتُ مِنْكَ فِي نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ",
    "rumi": "Allahumma inni asbahtu minka fi ni'matin wa 'afiyatin wa sitr, fa-atimma 'alayya ni'mataka wa 'afiyataka wa sitraka fid-dunya wal-akhirah.",
    "ms": "Ya Allah, pagi ini aku berada dalam nikmat, kesejahteraan dan perlindungan daripada-Mu. Maka sempurnakanlah ke atasku nikmat-Mu, kesejahteraan-Mu dan perlindungan-Mu di dunia dan akhirat.",
    "petang": {
      "ar": "اللّٰهُمَّ إِنِّي أَمْسَيْتُ مِنْكَ فِي نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ",
      "rumi": "Allahumma inni amsaitu minka fi ni'matin wa 'afiyatin wa sitr, fa-atimma 'alayya ni'mataka wa 'afiyataka wa sitraka fid-dunya wal-akhirah.",
      "ms": "Ya Allah, petang ini aku berada dalam nikmat, kesejahteraan dan perlindungan daripada-Mu. Maka sempurnakanlah ke atasku nikmat-Mu, kesejahteraan-Mu dan perlindungan-Mu di dunia dan akhirat."
    }
  },
  {
    "id": 15,
    "kind": "doa",
    "title": "Pengakuan segala nikmat daripada Allah",
    "repeat": 1,
    "ar": "اللّٰهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
    "rumi": "Allahumma ma asbaha bi min ni'matin au bi-ahadim min khalqika faminka wahdaka la syarika lak, falakal-hamdu wa lakasy-syukr.",
    "ms": "Ya Allah, apa jua nikmat yang ada padaku atau pada sesiapa pun daripada makhluk-Mu pada pagi ini, semuanya daripada-Mu semata-mata, tiada sekutu bagi-Mu. Maka bagi-Mu segala puji dan bagi-Mu segala syukur.",
    "petang": {
      "ar": "اللّٰهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
      "rumi": "Allahumma ma amsa bi min ni'matin au bi-ahadim min khalqika faminka wahdaka la syarika lak, falakal-hamdu wa lakasy-syukr.",
      "ms": "Ya Allah, apa jua nikmat yang ada padaku atau pada sesiapa pun daripada makhluk-Mu pada petang ini, semuanya daripada-Mu semata-mata, tiada sekutu bagi-Mu. Maka bagi-Mu segala puji dan bagi-Mu segala syukur."
    }
  },
  {
    "id": 16,
    "kind": "doa",
    "title": "Pujian bagi Allah",
    "repeat": 1,
    "ar": "يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ",
    "rumi": "Ya rabbi lakal-hamdu kama yanbaghi lijalali wajhika wa 'azimi sultanik.",
    "ms": "Wahai Tuhanku, bagi-Mu segala puji sebagaimana yang layak bagi keagungan wajah-Mu dan kebesaran kekuasaan-Mu."
  },
  {
    "id": 17,
    "kind": "doa",
    "title": "Ikrar keredaan",
    "repeat": 3,
    "ar": "رَضِيتُ بِاللّٰهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا وَرَسُولًا",
    "rumi": "Raditu billahi rabba, wa bil-islami dina, wa bi-Muhammadin sallallahu 'alaihi wa sallama nabiyyaw wa rasula.",
    "ms": "Aku reda Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad ﷺ sebagai nabi dan rasul."
  },
  {
    "id": 18,
    "kind": "doa",
    "title": "Tasbih",
    "repeat": 3,
    "ar": "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ، عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ",
    "rumi": "Subhanallahi wa bihamdih, 'adada khalqih, wa rida nafsih, wa zinata 'arsyih, wa midada kalimatih.",
    "ms": "Maha Suci Allah dan segala puji bagi-Nya, sebanyak bilangan makhluk-Nya, sebanyak yang meredakan diri-Nya, seberat 'Arasy-Nya, dan sebanyak tinta kalimah-kalimah-Nya."
  },
  {
    "id": 19,
    "kind": "doa",
    "title": "Berlindung dengan nama Allah",
    "repeat": 3,
    "ar": "بِسْمِ اللّٰهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ",
    "rumi": "Bismillahil-lazi la yadurru ma'asmihi syai'un fil-ardi wa la fis-sama', wa huwas-sami'ul-'alim.",
    "ms": "Dengan nama Allah, yang dengan nama-Nya tiada sesuatu pun di bumi dan di langit dapat memberi mudarat, dan Dialah Yang Maha Mendengar lagi Maha Mengetahui."
  },
  {
    "id": 20,
    "kind": "doa",
    "title": "Terhindar daripada syirik",
    "repeat": 3,
    "ar": "اللّٰهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ",
    "rumi": "Allahumma inna na'uzu bika min an nusyrika bika syai'an na'lamuh, wa nastaghfiruka lima la na'lamuh.",
    "ms": "Ya Allah, kami berlindung kepada-Mu daripada menyekutukan-Mu dengan sesuatu yang kami ketahui, dan kami memohon ampun kepada-Mu atas apa yang tidak kami ketahui."
  },
  {
    "id": 21,
    "kind": "doa",
    "title": "Berlindung daripada kejahatan makhluk",
    "repeat": 3,
    "ar": "أَعُوذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    "rumi": "A'uzu bikalimatillahit-tammati min syarri ma khalaq.",
    "ms": "Aku berlindung dengan kalimah-kalimah Allah yang sempurna daripada kejahatan makhluk yang Dia ciptakan."
  },
  {
    "id": 22,
    "kind": "doa",
    "title": "Terhindar daripada belenggu hutang",
    "repeat": 1,
    "ar": "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ",
    "rumi": "Allahumma inni a'uzu bika minal-hammi wal-hazan, wa a'uzu bika minal-'ajzi wal-kasal, wa a'uzu bika minal-jubni wal-bukhl, wa a'uzu bika min ghalabatid-daini wa qahrir-rijal.",
    "ms": "Ya Allah, aku berlindung kepada-Mu daripada rasa gelisah dan dukacita, daripada lemah dan malas, daripada sifat pengecut dan bakhil, serta daripada bebanan hutang dan penindasan manusia."
  },
  {
    "id": 23,
    "kind": "doa",
    "title": "Memohon kesihatan",
    "repeat": 3,
    "ar": "اللّٰهُمَّ عَافِنِي فِي بَدَنِي، اللّٰهُمَّ عَافِنِي فِي سَمْعِي، اللّٰهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلٰهَ إِلَّا أَنْتَ",
    "rumi": "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant.",
    "ms": "Ya Allah, sihatkanlah tubuh badanku. Ya Allah, sihatkanlah pendengaranku. Ya Allah, sihatkanlah penglihatanku. Tiada tuhan melainkan Engkau."
  },
  {
    "id": 24,
    "kind": "doa",
    "title": "Terhindar daripada kekufuran dan kefakiran",
    "repeat": 3,
    "ar": "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلٰهَ إِلَّا أَنْتَ",
    "rumi": "Allahumma inni a'uzu bika minal-kufri wal-faqr, Allahumma inni a'uzu bika min 'azabil-qabr, la ilaha illa ant.",
    "ms": "Ya Allah, aku berlindung kepada-Mu daripada kekufuran dan kefakiran. Ya Allah, aku berlindung kepada-Mu daripada azab kubur. Tiada tuhan melainkan Engkau."
  },
  {
    "id": 25,
    "kind": "doa",
    "title": "Sayyidul Istighfar",
    "repeat": 1,
    "ar": "اللّٰهُمَّ أَنْتَ رَبِّي، لَا إِلٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    "rumi": "Allahumma anta rabbi, la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'uzu bika min syarri ma sana't, abu'u laka bini'matika 'alayya, wa abu'u bizanbi, faghfir li, fa-innahu la yaghfiruz-zunuba illa ant.",
    "ms": "Ya Allah, Engkaulah Tuhanku, tiada tuhan melainkan Engkau. Engkau menciptakanku dan aku hamba-Mu. Aku berpegang pada janji dan ikrarku kepada-Mu sedaya upayaku. Aku berlindung kepada-Mu daripada keburukan perbuatanku. Aku mengakui nikmat-Mu ke atasku dan aku mengakui dosaku, maka ampunilah aku, kerana tiada yang mengampunkan dosa melainkan Engkau."
  },
  {
    "id": 26,
    "kind": "doa",
    "title": "Istighfar",
    "repeat": 3,
    "ar": "أَسْتَغْفِرُ اللّٰهَ الَّذِي لَا إِلٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    "rumi": "Astaghfirullahal-lazi la ilaha illa huwal-hayyul-qayyumu wa atubu ilaih.",
    "ms": "Aku memohon ampun kepada Allah, yang tiada tuhan melainkan Dia, Yang Maha Hidup lagi Maha Berdiri Sendiri, dan aku bertaubat kepada-Nya."
  },
  {
    "id": 27,
    "kind": "doa",
    "title": "Tasbih dan taubat",
    "repeat": 1,
    "ar": "سُبْحَانَكَ اللّٰهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلٰهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
    "rumi": "Subhanakallahumma wa bihamdik, asyhadu al-la ilaha illa ant, astaghfiruka wa atubu ilaik.",
    "ms": "Maha Suci Engkau ya Allah dan dengan memuji-Mu. Aku bersaksi bahawa tiada tuhan melainkan Engkau. Aku memohon ampun dan bertaubat kepada-Mu."
  },
  {
    "id": 28,
    "kind": "doa",
    "title": "Selawat ke atas Nabi ﷺ",
    "repeat": 1,
    "ar": "اللّٰهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ عَبْدِكَ وَنَبِيِّكَ وَرَسُولِكَ النَّبِيِّ الْأُمِّيِّ، وَعَلَى آلِهِ وَصَحْبِهِ وَسَلِّمْ تَسْلِيمًا، عَدَدَ مَا أَحَاطَ بِهِ عِلْمُكَ، وَخَطَّ بِهِ قَلَمُكَ، وَأَحْصَاهُ كِتَابُكَ",
    "rumi": "Allahumma salli 'ala sayyidina Muhammadin 'abdika wa nabiyyika wa rasulikan-nabiyyil-ummiyy, wa 'ala alihi wa sahbihi wa sallim taslima, 'adada ma ahata bihi 'ilmuk, wa khatta bihi qalamuk, wa ahsahu kitabuk.",
    "ms": "Ya Allah, limpahkanlah selawat ke atas penghulu kami Muhammad, hamba-Mu, nabi-Mu dan rasul-Mu, nabi yang ummi, serta ke atas keluarga dan para sahabatnya, dan kurniakanlah kesejahteraan yang sempurna, sebanyak apa yang diliputi oleh ilmu-Mu, ditulis oleh qalam-Mu dan dihitung oleh kitab-Mu."
  },
  {
    "id": 29,
    "kind": "doa",
    "title": "Keredaan ke atas para sahabat",
    "repeat": 1,
    "ar": "وَارْضَ اللّٰهُمَّ عَنْ سَادَاتِنَا أَبِي بَكْرٍ وَعُمَرَ وَعُثْمَانَ وَعَلِيٍّ، وَعَنِ الصَّحَابَةِ أَجْمَعِينَ، وَعَنِ التَّابِعِينَ وَتَابِعِيهِمْ بِإِحْسَانٍ إِلَى يَوْمِ الدِّينِ. سُبْحَانَ رَبِّكَ رَبِّ الْعِزَّةِ عَمَّا يَصِفُونَ، وَسَلَامٌ عَلَى الْمُرْسَلِينَ، وَالْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِينَ",
    "rumi": "Wardallahumma 'an sadatina Abi Bakrin wa 'Umara wa 'Usmana wa 'Aliyy, wa 'anis-sahabati ajma'in, wa 'anit-tabi'ina wa tabi'ihim bi-ihsanin ila yaumid-din. Subhana rabbika rabbil-'izzati 'amma yasifun, wa salamun 'alal-mursalin, wal-hamdu lillahi rabbil-'alamin.",
    "ms": "Dan redailah ya Allah, penghulu-penghulu kami Abu Bakar, Umar, Uthman dan Ali, serta seluruh para sahabat, para tabi'in dan pengikut mereka dengan kebaikan hingga hari pembalasan. Maha Suci Tuhanmu, Tuhan Yang Maha Perkasa, daripada apa yang mereka sifatkan. Kesejahteraan ke atas para rasul, dan segala puji bagi Allah, Tuhan sekalian alam."
  },
  {
    "id": 30,
    "kind": "doa",
    "title": "Doa selepas al-Mathurat",
    "repeat": 1,
    "ar": "اللّٰهُمَّ إِنَّا نَسْأَلُكَ لِسَانًا رَطْبًا بِذِكْرِكَ، وَقَلْبًا مُفْعَمًا بِشُكْرِكَ، وَبَدَنًا هَيِّنًا لَيِّنًا بِطَاعَتِكَ. اللّٰهُمَّ إِنَّا نَسْأَلُكَ إِيمَانًا كَامِلًا، وَنَسْأَلُكَ قَلْبًا خَاشِعًا، وَنَسْأَلُكَ عِلْمًا نَافِعًا، وَنَسْأَلُكَ يَقِينًا صَادِقًا، وَنَسْأَلُكَ دِينًا قَيِّمًا، وَنَسْأَلُكَ الْعَافِيَةَ مِنْ كُلِّ بَلِيَّةٍ، وَنَسْأَلُكَ تَمَامَ الْغِنَى عَنِ النَّاسِ، وَهَبْ لَنَا حَقِيقَةَ الْإِيمَانِ بِكَ حَتَّى لَا نَخَافَ وَلَا نَرْجُوَ غَيْرَكَ، وَلَا نَعْبُدَ شَيْئًا سِوَاكَ، وَاجْعَلْ يَدَكَ مَبْسُوطَةً عَلَيْنَا وَعَلَى أَهْلِنَا وَأَوْلَادِنَا وَمَنْ مَعَنَا بِرَحْمَتِكَ، وَلَا تَكِلْنَا إِلَى أَنْفُسِنَا طَرْفَةَ عَيْنٍ وَلَا أَقَلَّ مِنْ ذٰلِكَ، يَا نِعْمَ الْمُجِيبُ. وَصَلَّى اللّٰهُ عَلَى سَيِّدِنَا مُحَمَّدٍ النَّبِيِّ الْكَرِيمِ، وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ",
    "rumi": "Allahumma inna nas'aluka lisanan ratban bizikrik, wa qalbam muf'aman bisyukrik, wa badanan hayyinan layyinan bita'atik. Allahumma inna nas'aluka imanan kamila, wa nas'aluka qalban khasyi'a, wa nas'aluka 'ilman nafi'a, wa nas'aluka yaqinan sadiqa, wa nas'aluka dinan qayyima, wa nas'alukal-'afiyata min kulli baliyyah, wa nas'aluka tamamal-ghina 'anin-nas. Wa hab lana haqiqatal-imani bika hatta la nakhafa wa la narjuwa ghairak, wa la na'buda syai'an siwak. Waj'al yadaka mabsutatan 'alaina wa 'ala ahlina wa auladina wa man ma'ana birahmatik, wa la takilna ila anfusina tarfata 'ainin wa la aqalla min zalik, ya ni'mal-mujib. Wa sallallahu 'ala sayyidina Muhammadinin-nabiyyil-karim, wa 'ala alihi wa sahbihi ajma'in.",
    "ms": "Ya Allah, kami memohon kepada-Mu lidah yang sentiasa basah dengan zikir kepada-Mu, hati yang penuh dengan syukur kepada-Mu, dan tubuh yang mudah lagi lembut untuk mentaati-Mu. Ya Allah, kami memohon kepada-Mu iman yang sempurna, hati yang khusyuk, ilmu yang bermanfaat, keyakinan yang benar, agama yang lurus, kesejahteraan daripada segala bala, dan kecukupan yang sempurna sehingga tidak bergantung kepada manusia. Kurniakanlah kepada kami hakikat iman kepada-Mu sehingga kami tidak takut dan tidak berharap kepada selain-Mu, dan tidak menyembah sesuatu pun selain-Mu. Jadikanlah rahmat-Mu sentiasa terbentang ke atas kami, keluarga kami, anak-anak kami dan sesiapa yang bersama kami. Janganlah Engkau serahkan kami kepada diri kami sendiri walau sekelip mata, malah tidak juga kurang daripada itu, wahai sebaik-baik Yang Memperkenankan doa. Semoga Allah melimpahkan selawat ke atas penghulu kami Muhammad, Nabi yang mulia, serta ke atas keluarga dan sahabat baginda semuanya."
  }
];
